### ISSUE TITLE
Unable to detect known vulnerability in gradle plugin

### ISSUE THREAD

**Issue by ajaytestacc** [jeremylong/dependency-check-gradle#16]
I am using gradle plugin to detect known issue but it unable to find known issue(CVE-2016-3720) in jackson-dataformat-xml-2.7.0.jar.

same thing is working fine with maven plugin.

**Comment by jeremylong** [comment]
Can you share your configuration? What version are you using?  I just tested this with the current snapshot (1.4.3-SNAPSHOT) and it detected the vulnerability. See attached:
[gradel-test.zip](https://github.com/jeremylong/dependency-check-gradle/files/454979/gradel-test.zip)

**Comment by ajaytestacc** [comment]
Version: 1.4.2
`apply plugin: "org.owasp.dependencycheck"
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.org.owasp:dependency-check-gradle:1.4.2"
  }
}`

<img width="1320" alt="screen shot 2016-09-06 at 12 54 26 pm" src="https://cloud.githubusercontent.com/assets/20664733/18264933/ac04a220-7430-11e6-9c65-9e52a0a2e592.png">

**Comment by ajaytestacc** [comment]
Thanks @jeremylong 
Updated current version `org.owasp:dependency-check-gradle:1.4.3` and it working now

**Comment by stefanneuhaus** [comment]
# Observations:
I observed a very similar issue with 1.4.2:
* Locally `dependencyCheckUpdate` failed reproducibly  saying `Unable to connect to the dependency-check database`. Though the fetched database had a reasonable size of ~265 MB. `dependencyCheck` successfully detected a bunch of vulnerabilities, but it did not detect CVE-2016-3720.
* On the CI server CVE-2016-3720 was detected.

After upgrade to 1.4.3:
* Locally `dependencyCheck` still did not detect CVE-2016-3720 (with the presumably corrupted DB). But now it detected CVE-2015-6420 for the first time.
* After clearing the DB, `dependencyCheckUpdate` successfully fetched the DB and `dependencyCheck` detected CVE-2016-3720. It also detected CVE-2016-3092 for the first time. I could verify this behavior twice in a row.

# Conclusion:
Regarding this _"Unable to detect known vulnerability in gradle plugin"_ issue, to me it seems like 1.4.3 fixed some issue with fetching the database, which was the actual root cause.

**Comment by jeremylong** [comment]
Your conclusion is correct. I will be posting information about this on the mailing list and twitter shortly. I am just waiting for the updated Jenkins plugin to be updated.
